### ISSUE TITLE
Errors on npm run serve

### ISSUE THREAD

**Issue by jayypluss** [jareddantis/playman#2]
I'm repeatedly getting those erros on running npm run serve.

Steps to reproduce: 
1. Run `npm install`
2. Run `npm run serve`

```
Request from ::1: GET /json
Response with status 500 in 1 ms.
Error during invocation:  { Error: Cannot find module '/home/jonathanfk/Dev/playman/lambda/json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/jonathanfk/Dev/playman/node_modules/netlify-lambda/lib/serve.js:24:17
    at Layer.handle [as handle_request] (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:137:13)
    at next (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:131:14)
    at next (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:131:14)
    at next (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:131:14)
    at next (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:131:14)
    at next (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:131:14)
    at next (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/layer.js:95:5)
    at /home/jonathanfk/Dev/playman/node_modules/express/lib/router/index.js:281:22 code: 'MODULE_NOT_FOUND' }
Request from ::1: GET /json/version
Response with status 500 in 1 ms.
Error during invocation:  { Error: Cannot find module '/home/jonathanfk/Dev/playman/lambda/json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/jonathanfk/Dev/playman/node_modules/netlify-lambda/lib/serve.js:24:17
    at Layer.handle [as handle_request] (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:137:13)
    at next (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:131:14)
    at next (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:131:14)
    at next (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:131:14)
    at next (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:131:14)
    at next (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:131:14)
    at next (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/jonathanfk/Dev/playman/node_modules/express/lib/router/layer.js:95:5)
    at /home/jonathanfk/Dev/playman/node_modules/express/lib/router/index.js:281:22 code: 'MODULE_NOT_FOUND' }

```

System info: 
```
 OS: Antergos 
 Kernel: x86_64 Linux 5.5.9-arch1-2
 Uptime: 2d 6h 43m
 Packages: 1271
 Shell: zsh 5.8
 Resolution: 3286x1287
 DE: Cinnamon 4.4.8
 WM: Muffin
 WM Theme: Numix-Cinnamon-Transparent (Numix-Frost)
 GTK Theme: Numix-Frost-Light [GTK2/3]
 Icon Theme: Flat-Remix-Blue-Dark
 Font: Sans 9
 Disk: 176G / 224G (80%)
 CPU: Intel Core i5-7200U @ 4x 2.5GHz [53.0°C]
 GPU: Intel Corporation HD Graphics 620 (rev 02)
 RAM: 16549MiB / 19963MiB

```

**Comment by jareddantis** [comment]
Hi @jayypluss! This is awfully awkward but I had to recently unarchive Playman because of a domain change (it's live at [playman.dantis.me](https://playman.dantis.me)) and I just saw this now.

Unfortunately I couldn't reproduce this on a fresh clone, however I did make some fixes to the dependency versions and updates to README, which might help if you're still tinkering with Playman. I was able to run `yarn run serve` properly when I tried it today.

Thanks and apologies for the late reply!
